name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Bump version
        run: pnpm version ${{ github.event.inputs.bump }} --no-git-tag-version

      - name: Build package
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit version bump
        run: |
          git config user.name "Release Bot"
          git config user.email "noreply@github.com"
          git add package.json package-lock.json
          git commit -m "ci: bump version [skip ci]"
          git push
